### ISSUE TITLE
Unable to see the code coverage result on sonarqube

### ISSUE THREAD

**Issue by vishalgoyal16444** [tkgregory/sonarqube-jacoco-code-coverage#1]
We tried using the repository to generate the result on sonarqube. We have sonarqube running inside the container.
After running the code we get the build folder generated which have the reports generated:
![image](https://user-images.githubusercontent.com/73927117/113387150-59c87e80-93a9-11eb-813f-58f73fc9490b.png)
We have following reports inside build:
![image](https://user-images.githubusercontent.com/73927117/113387233-88def000-93a9-11eb-896e-e85bd97a02ba.png)
Inside the jacoco folder the test.exec is being generated.
As we aim to view the coverage result on sonarqube, any xml file is not being generated which can be provided to sonarqube.
![image](https://user-images.githubusercontent.com/73927117/113387506-16224480-93aa-11eb-9a94-374a7146c74e.png)
Can you please advise on how do we get the code coverage..

**Comment by jamie-houston** [comment]
I figured out the issue.  Looks like jacoco doesn't export xml by default anymore, so it needs this flag set.  I created a PR with the fix. https://github.com/tkgregory/sonarqube-jacoco-code-coverage/pull/2

**Comment by tkgregory** [comment]
Closing as this change has already been incorporated into this project.
